In [ ]:
from sklearn.linear_model import Perceptron
x = [[0,0],[0,1],[1,0],[1,1]]
t = [0,1,1,1]
model = Perceptron()
model.fit(x,t)
model.score(x,t)
x1 = [[0.5,-1],[0.5,0.5],[-10,1]]
y1 = model.predict(x1)
model.score(x1,y1)

1.0

In [ ]:
from sklearn.linear_model import Perceptron
x = [[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
y = [1,1,0,0]
model = Perceptron()
model.fit(x,y)
model.score(x,y)
x1 = [[0.5,-1],[0.5,0.5],[-10,1]]
y1 = model.predict(x1)
model.score(x1,y1)

1.0

In [ ]:
from sklearn                  import datasets
from sklearn.linear_model     import Perceptron
from sklearn.model_selection  import train_test_split
from sklearn.metrics          import accuracy_score
from sklearn.preprocessing    import StandardScaler
iris = datasets.load_iris()
X = iris.data
y = iris.target
print(X[:5])
print(y[:5])
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std  = sc.transform(X_test)

model = Perceptron(max_iter = 40, eta0 = 0.1, random_state = 0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Do chinh xac cua mo hinh', accuracy_score(y_test, y_pred))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[0 2 0 2 1 0 2 2 0 1 2 0 2 2 2 1 1 1 0 0 0 0 2 1 2 2 2 1 2 0 2 0 2 2 0 2 2
 2 1 2 0 0 0 0 0]
[0 1 0 2 1 1 1 2 0 1 2 0 2 1 1 1 1 1 0 0 0 0 1 1 2 2 2 1 2 0 2 0 1 2 0 2 2
 1 1 2 0 0 0 0 1]
Do chinh xac cua mo hinh 0.8


In [ ]:
from sklearn                  import datasets
from sklearn.linear_model     import Perceptron
from sklearn.model_selection  import train_test_split
from sklearn.metrics          import accuracy_score
from sklearn.preprocessing    import StandardScaler

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sas
data = pd.read_csv('crabs.csv')
data_B = data[data['speies']=='B']
data_B.groupby('speies')
data_B


speies sex  index  fontallip  rearwidth  length  width  depth
0       B   M      1        8.1        6.7    16.1   19.0    7.0
1       B   M      2        8.8        7.7    18.1   20.8    7.4
2       B   M      3        9.2        7.8    19.0   22.4    7.7
3       B   M      4        9.6        7.9    20.1   23.1    8.2
4       B   M      5        9.8        8.0    20.3   23.0    8.2
..    ...  ..    ...        ...        ...     ...    ...    ...
95      B   F     46       16.4       14.0    34.2   39.8   15.2
96      B   F     47       16.7       16.1    36.6   41.9   15.4
97      B   F     48       17.4       16.9    38.2   44.1   16.6
98      B   F     49       17.5       16.7    38.6   44.5   17.0
99      B   F     50       19.2       16.5    40.9   47.9   18.1

[100 rows x 8 columns]